POST http://localhost:3000/transactions HTTP/1.1
content-type: application/json

{
    "userId": 123,
    "fromCurrency": "BRL",
    "toCurrency": "EUR",
    "fromValue": 100
}

###

GET http://localhost:3000/transactions/?userId=1 HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

