POST https://currency-converter-node.onrender.com/transactions HTTP/1.1
content-type: application/json

{
    "userId": 1234,
    "fromCurrency": "USD",
    "toCurrency": "BRL",
    "fromValue": 1
}

###

GET https://currency-converter-node.onrender.com/transactions?userId=123 HTTP/1.1
content-type: application/json


